from langchain.tools import tool
from pydantic import BaseModel
from sqlalchemy import select
from datetime import datetime, date as date_type
from typing import Literal
from uuid import UUID

from app.core.database import SyncSessionLocal
from app.core.security import get_password_hash
from app.models.auth import User
from app.models.dev_tracking import DevInvestment, DevProject, ProjectDownload
from app.models.finance import ExpenseType, Finance
from app.models.hr import AttendanceLog, Department, LeaveRequest, Paycheck
from app.models.scm import Product


##### COMMON #####
class DeleteOutput(BaseModel):
    id: int | UUID
    message: str


##### AUTH #####
class UserInfo(BaseModel):
    id: int | None = None
    full_name: str | None = None
    email: str | None = None
    is_active: bool | None = None
    has_finance_access: bool | None = None
    has_scm_access: bool | None = None
    has_hr_access: bool | None = None
    has_dev_access: bool | None = None

class GetUserOutput(BaseModel):
    user_detail: list[UserInfo]
    total: int


@tool
def get_user_info(
    target_user_id: int | None = None,
    target_user_name: str | None = None,
    has_finance_access: bool | None = None,
    has_scm_access: bool | None = None,
    has_hr_access: bool | None = None,
    has_dev_access: bool | None = None,
) -> GetUserOutput | None:
    """
    Gets user information from database table "users", filtered by parameters that is not None
    Args:
        target_user_id: Target user ID to query, None if not filter by ID
        target_user_name: Target user full name (exact match), None if not filter by name
        has_finance_access: Filter user with finance access, None if do not want to filter by finance access
        has_scm_access: Filter user with SCM access, None if do not want to filter by SCM access
        has_hr_access: Filter user with HR access, None if do not want to filter by HR access
        has_dev_access: Filter user with dev access, None if do not want to filter by dev access

    Returns:
        Every user that fits the condition listed in `GetUserOutput.user_detail` with count in `total`, all users if no filter given, None if no user fits
    """
    stmt = select(User)
    if target_user_id is not None:
        stmt = stmt.where(User.id == target_user_id)
    if target_user_name is not None:
        stmt = stmt.where(User.full_name == target_user_name)
    if has_finance_access is not None:
        stmt = stmt.where(User.has_finance_access == has_finance_access)
    if has_scm_access is not None:
        stmt = stmt.where(User.has_scm_access == has_scm_access)
    if has_hr_access is not None:
        stmt = stmt.where(User.has_hr_access == has_hr_access)
    if has_dev_access is not None:
        stmt = stmt.where(User.has_dev_access == has_dev_access)

    with SyncSessionLocal() as session:
        users = (session.execute(stmt)).scalars().all()

    if not users:
        return None
    return GetUserOutput(
        user_detail=[UserInfo.model_validate(u, from_attributes=True) for u in users],
        total=len(users),
    )

@tool
def create_user(
    new_user_email: str,
    password: str,
    full_name: str | None = None,
    is_active: bool = True,
    has_finance_access: bool = False,
    has_scm_access: bool = False,
    has_hr_access: bool = False,
    has_dev_access: bool = False,
) -> UserInfo:
    """
    Creates a new user into database table "users", user ID is generated by default, password will be hashed and original password will not be saved, permissions default to False if not given
    Args:
        new_user_email: User email to create, this value will be the account when login, must not already exist
        password: Plain text password of user, will be hashed before saving
        full_name: Full name of user, None if not given
        is_active: Whether the user can log in, defaults to True
        has_finance_access: Permission of newly created user with finance access
        has_scm_access: Permission of newly created user with SCM access
        has_hr_access: Permission of newly created user with HR access
        has_dev_access: Permission of newly created user with dev access

    Returns:
        The created user record
    """
    with SyncSessionLocal() as session:
        existing_user = session.execute(select(User).where(User.email == new_user_email)).scalar_one_or_none()
        if existing_user is not None:
            raise ValueError(f'User with email {new_user_email} already exists')

        user = User(
            email=new_user_email,
            hashed_password=get_password_hash(password),
            full_name=full_name,
            is_active=is_active,
            has_finance_access=has_finance_access,
            has_scm_access=has_scm_access,
            has_hr_access=has_hr_access,
            has_dev_access=has_dev_access,
        )
        session.add(user)
        session.commit()
        session.refresh(user)

    return UserInfo.model_validate(user, from_attributes=True)

@tool
def update_user(
    target_user_id: int,
    full_name: str | None = None,
    email: str | None = None,
    password: str | None = None,
    is_active: bool | None = None,
    has_finance_access: bool | None = None,
    has_scm_access: bool | None = None,
    has_hr_access: bool | None = None,
    has_dev_access: bool | None = None,
) -> UserInfo:
    """
    Updates an existing user in database table "users", only fields that is not None are changed
    Args:
        target_user_id: ID of the user to update
        full_name: New full name, None if not change
        email: New login email, must not be used by another user, None if not change
        password: New plain text password, will be hashed before saving, None if not change
        is_active: Whether the user can log in, None if not change
        has_finance_access: New finance access permission, None if not change
        has_scm_access: New SCM access permission, None if not change
        has_hr_access: New HR access permission, None if not change
        has_dev_access: New dev access permission, None if not change

    Returns:
        The updated user record
    """
    with SyncSessionLocal() as session:
        user = session.get(User, target_user_id)
        if user is None:
            raise ValueError(f'User with id {target_user_id} not found')
        if email is not None and email != user.email:
            existing_user = session.execute(select(User).where(User.email == email)).scalar_one_or_none()
            if existing_user is not None:
                raise ValueError(f'User with email {email} already exists')
            user.email = email
        if full_name is not None:
            user.full_name = full_name
        if password is not None:
            user.hashed_password = get_password_hash(password)
        if is_active is not None:
            user.is_active = is_active
        if has_finance_access is not None:
            user.has_finance_access = has_finance_access
        if has_scm_access is not None:
            user.has_scm_access = has_scm_access
        if has_hr_access is not None:
            user.has_hr_access = has_hr_access
        if has_dev_access is not None:
            user.has_dev_access = has_dev_access
        session.commit()
        session.refresh(user)

    return UserInfo.model_validate(user, from_attributes=True)

@tool
def delete_user(target_user_id: int) -> DeleteOutput:
    """
    Deletes a user from database table "users", attendance logs, leave requests and paychecks of the user are deleted with it
    Args:
        target_user_id: ID of the user to delete

    Returns:
        ID of the deleted user with a confirmation message
    """
    with SyncSessionLocal() as session:
        user = session.get(User, target_user_id)
        if user is None:
            raise ValueError(f'User with id {target_user_id} not found')
        session.delete(user)
        session.commit()

    return DeleteOutput(id=target_user_id, message=f'User {target_user_id} deleted')

##### FINANCE #####
class ExpenseDetail(BaseModel):
    id: UUID
    expense_type: ExpenseType
    amount: float
    created_at: datetime
    updated_at: datetime

class GetExpensesOutput(BaseModel):
    expense_detail: list[ExpenseDetail]
    total: float

@tool
def get_expenses(
    start_date: datetime | None = None,
    end_date: datetime | None = None,
    expense_type: Literal["paycheck", "petty_cash", "investment", "other"] | None = None,
) -> GetExpensesOutput | None:
    """
    Gets expenses data from database table "finance", filtered by parameters that is not None
    Args:
        start_date: Start period to query expenses (inclusive, by created_at), None if not filter by start date
        end_date: End period to query expenses (inclusive, by created_at), None if not filter by end date
        expense_type: Specify which type of expenses to filter by, None if not filter by type

    Returns:
        Expenses data, each expense listed in `GetExpensesOutput.expense_detail` with summed amount in `total`, None if no expenses found with filter given
    """
    stmt = select(Finance)
    if start_date is not None:
        stmt = stmt.where(Finance.created_at >= start_date)
    if end_date is not None:
        stmt = stmt.where(Finance.created_at <= end_date)
    if expense_type is not None:
        stmt = stmt.where(Finance.expense_type == ExpenseType(expense_type))

    with SyncSessionLocal() as session:
        expenses = (session.execute(stmt)).scalars().all()

    if not expenses:
        return None
    total = float(sum(e.amount for e in expenses))
    return GetExpensesOutput(
        expense_detail=[ExpenseDetail.model_validate(e, from_attributes=True) for e in expenses],
        total=total,
    )

@tool
def create_expense(
    expense_type: Literal["paycheck", "petty_cash", "investment", "other"],
    amount: float,
) -> ExpenseDetail:
    """
    Creates a new expense record into database table "finance"
    Args:
        expense_type: Type of the expense to create
        amount: Amount of the expense to create

    Returns:
        The created expense record
    """
    expense = Finance(expense_type=ExpenseType(expense_type), amount=amount)

    with SyncSessionLocal() as session:
        session.add(expense)
        session.commit()
        session.refresh(expense)

    return ExpenseDetail.model_validate(expense, from_attributes=True)

@tool
def update_expense(
    expense_id: UUID,
    expense_type: Literal["paycheck", "petty_cash", "investment", "other"] | None = None,
    amount: float | None = None,
) -> ExpenseDetail:
    """
    Updates an existing expense record in database table "finance", only fields that is not None are changed
    Args:
        expense_id: UUID of the expense to update
        expense_type: New type of the expense, None if not change
        amount: New amount of the expense, None if not change

    Returns:
        The updated expense record
    """
    with SyncSessionLocal() as session:
        expense = session.get(Finance, expense_id)
        if expense is None:
            raise ValueError(f'Expense with id {expense_id} not found')
        if expense_type is not None:
            expense.expense_type = ExpenseType(expense_type)
        if amount is not None:
            expense.amount = amount
        session.commit()
        session.refresh(expense)

    return ExpenseDetail.model_validate(expense, from_attributes=True)

@tool
def delete_expense(expense_id: UUID) -> DeleteOutput:
    """
    Deletes an expense record from database table "finance"
    Args:
        expense_id: UUID of the expense to delete

    Returns:
        ID of the deleted expense with a confirmation message
    """
    with SyncSessionLocal() as session:
        expense = session.get(Finance, expense_id)
        if expense is None:
            raise ValueError(f'Expense with id {expense_id} not found')
        session.delete(expense)
        session.commit()

    return DeleteOutput(id=expense_id, message=f'Expense {expense_id} deleted')

##### SCM #####
class ProductDetail(BaseModel):
    id: int
    sku: str
    name: str
    description: str | None
    unit_price: float
    cost: float
    created_at: datetime
    updated_at: datetime

class GetProductsOutput(BaseModel):
    product_detail: list[ProductDetail]
    total: int

@tool
def get_products(
    product_id: int | None = None,
    sku: str | None = None,
    name: str | None = None,
) -> GetProductsOutput | None:
    """
    Gets product information from database table "products", filtered by parameters that is not None
    Args:
        product_id: Target product ID to query, None if not filter by ID
        sku: Target product SKU (exact match), None if not filter by SKU
        name: Part of the product name (case-insensitive contains), None if not filter by name

    Returns:
        Product data, each product listed in `GetProductsOutput.product_detail` with count in `total`, None if no product fits condition
    """
    stmt = select(Product)
    if product_id is not None:
        stmt = stmt.where(Product.id == product_id)
    if sku is not None:
        stmt = stmt.where(Product.sku == sku)
    if name is not None:
        stmt = stmt.where(Product.name.ilike(f'%{name}%'))

    with SyncSessionLocal() as session:
        products = (session.execute(stmt)).scalars().all()

    if not products:
        return None
    return GetProductsOutput(
        product_detail=[ProductDetail.model_validate(p, from_attributes=True) for p in products],
        total=len(products),
    )

@tool
def create_product(
    sku: str,
    name: str,
    description: str | None = None,
    unit_price: float = 0.0,
    cost: float = 0.0,
) -> ProductDetail:
    """
    Creates a new product into database table "products"
    Args:
        sku: Stock keeping unit code, must not already exist
        name: Product name
        description: Product description, None if not given
        unit_price: Selling price per unit, defaults to 0
        cost: Purchase cost per unit, defaults to 0

    Returns:
        The created product record
    """
    with SyncSessionLocal() as session:
        existing_product = session.execute(select(Product).where(Product.sku == sku)).scalar_one_or_none()
        if existing_product is not None:
            raise ValueError(f'Product with sku {sku} already exists')

        product = Product(sku=sku, name=name, description=description, unit_price=unit_price, cost=cost)
        session.add(product)
        session.commit()
        session.refresh(product)

    return ProductDetail.model_validate(product, from_attributes=True)

@tool
def update_product(
    product_id: int,
    sku: str | None = None,
    name: str | None = None,
    description: str | None = None,
    unit_price: float | None = None,
    cost: float | None = None,
) -> ProductDetail:
    """
    Updates an existing product in database table "products", only fields that is not None are changed
    Args:
        product_id: ID of the product to update
        sku: New SKU, must not be used by another product, None if not change
        name: New product name, None if not change
        description: New description, None if not change
        unit_price: New selling price per unit, None if not change
        cost: New purchase cost per unit, None if not change

    Returns:
        The updated product record
    """
    with SyncSessionLocal() as session:
        product = session.get(Product, product_id)
        if product is None:
            raise ValueError(f'Product with id {product_id} not found')
        if sku is not None and sku != product.sku:
            existing_product = session.execute(select(Product).where(Product.sku == sku)).scalar_one_or_none()
            if existing_product is not None:
                raise ValueError(f'Product with sku {sku} already exists')
            product.sku = sku
        if name is not None:
            product.name = name
        if description is not None:
            product.description = description
        if unit_price is not None:
            product.unit_price = unit_price
        if cost is not None:
            product.cost = cost
        session.commit()
        session.refresh(product)

    return ProductDetail.model_validate(product, from_attributes=True)

@tool
def delete_product(product_id: int) -> DeleteOutput:
    """
    Deletes a product from database table "products"
    Args:
        product_id: ID of the product to delete

    Returns:
        ID of the deleted product with a confirmation message
    """
    with SyncSessionLocal() as session:
        product = session.get(Product, product_id)
        if product is None:
            raise ValueError(f'Product with id {product_id} not found')
        session.delete(product)
        session.commit()

    return DeleteOutput(id=product_id, message=f'Product {product_id} deleted')

##### DEV-TRACKING #####
class DevProjectDetail(BaseModel):
    project_id: int
    project_name: str
    project_description: str | None
    created_at: datetime
    updated_at: datetime

class GetDevProjectOutput(BaseModel):
    project_detail: list[DevProjectDetail]
    total: int

@tool
def get_dev_project(
    project_id: int | None = None,
    project_name: str | None = None,
) -> GetDevProjectOutput | None:
    """
    Gets dev project information from database table "dev_projects", filtered by parameters that is not None
    Args:
        project_id: Target project ID to query, None if not filter by ID
        project_name: Target project name to query, None if not filter by name

    Returns:
        Dev project data, each project listed in `GetDevProjectOutput.project_detail` with count in `total`, None if no project fits condition
    """
    stmt = select(DevProject)
    if project_id is not None:
        stmt = stmt.where(DevProject.project_id == project_id)
    if project_name is not None:
        stmt = stmt.where(DevProject.project_name == project_name)

    with SyncSessionLocal() as session:
        projects = (session.execute(stmt)).scalars().all()

    if not projects:
        return None
    return GetDevProjectOutput(
        project_detail=[DevProjectDetail.model_validate(p, from_attributes=True) for p in projects],
        total=len(projects),
    )

@tool
def create_dev_project(project_name: str, project_description: str | None = None) -> DevProjectDetail:
    """
    Creates a new dev project into database table "dev_projects", project ID is generated by default
    Args:
        project_name: Name of the project
        project_description: Description of the project, None if not given

    Returns:
        The created dev project record
    """
    project = DevProject(project_name=project_name, project_description=project_description)

    with SyncSessionLocal() as session:
        session.add(project)
        session.commit()
        session.refresh(project)

    return DevProjectDetail.model_validate(project, from_attributes=True)

@tool
def update_dev_project(
    project_id: int,
    project_name: str | None = None,
    project_description: str | None = None,
) -> DevProjectDetail:
    """
    Updates an existing dev project in database table "dev_projects", only fields that is not None are changed
    Args:
        project_id: ID of the project to update
        project_name: New project name, None if not change
        project_description: New project description, None if not change

    Returns:
        The updated dev project record
    """
    with SyncSessionLocal() as session:
        project = session.get(DevProject, project_id)
        if project is None:
            raise ValueError(f'Dev project with id {project_id} not found')
        if project_name is not None:
            project.project_name = project_name
        if project_description is not None:
            project.project_description = project_description
        session.commit()
        session.refresh(project)

    return DevProjectDetail.model_validate(project, from_attributes=True)

@tool
def delete_dev_project(project_id: int) -> DeleteOutput:
    """
    Deletes a dev project from database table "dev_projects", investments and download snapshots of the project are deleted with it
    Args:
        project_id: ID of the project to delete

    Returns:
        ID of the deleted project with a confirmation message
    """
    with SyncSessionLocal() as session:
        project = session.get(DevProject, project_id)
        if project is None:
            raise ValueError(f'Dev project with id {project_id} not found')
        session.delete(project)
        session.commit()

    return DeleteOutput(id=project_id, message=f'Dev project {project_id} deleted')

class DevInvestmentDetail(BaseModel):
    id: int
    date: date_type
    project_id: int
    amount: float
    vendor: str | None
    category: str
    description: str | None
    created_at: datetime
    updated_at: datetime

class GetDevInvestmentOutput(BaseModel):
    investment_detail: list[DevInvestmentDetail]
    total: float

@tool
def get_dev_investment(
    project_id: int | None = None,
    start_date: date_type | None = None,
    end_date: date_type | None = None,
    vendor: str | None = None,
    category: str | None = None,
) -> GetDevInvestmentOutput | None:
    """
    Gets dev investment data from database table "dev_investments", filtered by parameters that is not None
    Args:
        project_id: Project ID the investments belong to, None if not filter by project
        start_date: Start period to query investments (inclusive, by date), None if not filter by start date
        end_date: End period to query investments (inclusive, by date), None if not filter by end date
        vendor: Vendor of the investments (e.g. AWS, GCP, Vercel), None if not filter by vendor
        category: Category of the investments (e.g. cloud, software_licenses, hardware, consulting), None if not filter by category

    Returns:
        Dev investment data, each investment listed in `GetDevInvestmentOutput.investment_detail` with summed amount in `total`, None if no investments found with filter given
    """
    stmt = select(DevInvestment)
    if project_id is not None:
        stmt = stmt.where(DevInvestment.project_id == project_id)
    if start_date is not None:
        stmt = stmt.where(DevInvestment.date >= start_date)
    if end_date is not None:
        stmt = stmt.where(DevInvestment.date <= end_date)
    if vendor is not None:
        stmt = stmt.where(DevInvestment.vendor == vendor)
    if category is not None:
        stmt = stmt.where(DevInvestment.category == category)

    with SyncSessionLocal() as session:
        investments = (session.execute(stmt)).scalars().all()

    if not investments:
        return None
    total = float(sum(i.amount for i in investments))
    return GetDevInvestmentOutput(
        investment_detail=[DevInvestmentDetail.model_validate(i, from_attributes=True) for i in investments],
        total=total,
    )

@tool
def create_dev_investment(
    project_id: int,
    date: date_type,
    amount: float,
    category: Literal["cloud", "software_licenses", "hardware", "consulting"] = "cloud",
    vendor: str | None = None,
    description: str | None = None,
) -> DevInvestmentDetail:
    """
    Creates a new dev investment into database table "dev_investments"
    Args:
        project_id: ID of the project the investment belongs to, must exist
        date: Date of the investment
        amount: Amount of the investment
        category: Category of the investment, defaults to cloud
        vendor: Vendor of the investment (e.g. AWS, GCP, Vercel), None if not given
        description: Description of the investment, None if not given

    Returns:
        The created dev investment record
    """
    with SyncSessionLocal() as session:
        project = session.get(DevProject, project_id)
        if project is None:
            raise ValueError(f'Dev project with id {project_id} not found')

        investment = DevInvestment(
            project_id=project_id,
            date=date,
            amount=amount,
            category=category,
            vendor=vendor,
            description=description,
        )
        session.add(investment)
        session.commit()
        session.refresh(investment)

    return DevInvestmentDetail.model_validate(investment, from_attributes=True)

@tool
def update_dev_investment(
    investment_id: int,
    project_id: int | None = None,
    date: date_type | None = None,
    amount: float | None = None,
    category: Literal["cloud", "software_licenses", "hardware", "consulting"] | None = None,
    vendor: str | None = None,
    description: str | None = None,
) -> DevInvestmentDetail:
    """
    Updates an existing dev investment in database table "dev_investments", only fields that is not None are changed
    Args:
        investment_id: ID of the investment to update
        project_id: New project ID the investment belongs to, must exist, None if not change
        date: New date of the investment, None if not change
        amount: New amount of the investment, None if not change
        category: New category of the investment, None if not change
        vendor: New vendor of the investment, None if not change
        description: New description of the investment, None if not change

    Returns:
        The updated dev investment record
    """
    with SyncSessionLocal() as session:
        investment = session.get(DevInvestment, investment_id)
        if investment is None:
            raise ValueError(f'Dev investment with id {investment_id} not found')
        if project_id is not None:
            project = session.get(DevProject, project_id)
            if project is None:
                raise ValueError(f'Dev project with id {project_id} not found')
            investment.project_id = project_id
        if date is not None:
            investment.date = date
        if amount is not None:
            investment.amount = amount
        if category is not None:
            investment.category = category
        if vendor is not None:
            investment.vendor = vendor
        if description is not None:
            investment.description = description
        session.commit()
        session.refresh(investment)

    return DevInvestmentDetail.model_validate(investment, from_attributes=True)

@tool
def delete_dev_investment(investment_id: int) -> DeleteOutput:
    """
    Deletes a dev investment from database table "dev_investments"
    Args:
        investment_id: ID of the investment to delete

    Returns:
        ID of the deleted investment with a confirmation message
    """
    with SyncSessionLocal() as session:
        investment = session.get(DevInvestment, investment_id)
        if investment is None:
            raise ValueError(f'Dev investment with id {investment_id} not found')
        session.delete(investment)
        session.commit()

    return DeleteOutput(id=investment_id, message=f'Dev investment {investment_id} deleted')

class ProjectDownloadDetail(BaseModel):
    id: int
    project_id: int
    date: date_type
    platform: str
    download_count: int
    star_count: int | None
    created_at: datetime
    updated_at: datetime

class GetProjectDownloadsOutput(BaseModel):
    download_detail: list[ProjectDownloadDetail]
    total: int

@tool
def get_project_downloads(
    project_id: int | None = None,
    platform: Literal["github", "dockerhub", "npm"] | None = None,
    start_date: date_type | None = None,
    end_date: date_type | None = None,
) -> GetProjectDownloadsOutput | None:
    """
    Gets download snapshots from database table "dev_project_downloads", filtered by parameters that is not None
    Args:
        project_id: Project ID the snapshots belong to, None if not filter by project
        platform: Platform of the snapshots, None if not filter by platform
        start_date: Start period to query snapshots (inclusive, by date), None if not filter by start date
        end_date: End period to query snapshots (inclusive, by date), None if not filter by end date

    Returns:
        Download snapshot data, each snapshot listed in `GetProjectDownloadsOutput.download_detail` with summed download count in `total`, None if no snapshot fits condition
    """
    stmt = select(ProjectDownload)
    if project_id is not None:
        stmt = stmt.where(ProjectDownload.project_id == project_id)
    if platform is not None:
        stmt = stmt.where(ProjectDownload.platform == platform)
    if start_date is not None:
        stmt = stmt.where(ProjectDownload.date >= start_date)
    if end_date is not None:
        stmt = stmt.where(ProjectDownload.date <= end_date)

    with SyncSessionLocal() as session:
        downloads = (session.execute(stmt)).scalars().all()

    if not downloads:
        return None
    return GetProjectDownloadsOutput(
        download_detail=[ProjectDownloadDetail.model_validate(d, from_attributes=True) for d in downloads],
        total=sum(d.download_count for d in downloads),
    )

@tool
def create_project_download(
    project_id: int,
    date: date_type,
    platform: Literal["github", "dockerhub", "npm"] = "github",
    download_count: int = 0,
    star_count: int | None = None,
) -> ProjectDownloadDetail:
    """
    Creates a new download snapshot into database table "dev_project_downloads"
    Args:
        project_id: ID of the project the snapshot belongs to, must exist
        date: Date of the snapshot
        platform: Platform of the snapshot, defaults to github
        download_count: Download count on that date, defaults to 0
        star_count: Star count on that date, None if not given

    Returns:
        The created download snapshot record
    """
    with SyncSessionLocal() as session:
        project = session.get(DevProject, project_id)
        if project is None:
            raise ValueError(f'Dev project with id {project_id} not found')

        download = ProjectDownload(
            project_id=project_id,
            date=date,
            platform=platform,
            download_count=download_count,
            star_count=star_count,
        )
        session.add(download)
        session.commit()
        session.refresh(download)

    return ProjectDownloadDetail.model_validate(download, from_attributes=True)

@tool
def update_project_download(
    download_id: int,
    project_id: int | None = None,
    date: date_type | None = None,
    platform: Literal["github", "dockerhub", "npm"] | None = None,
    download_count: int | None = None,
    star_count: int | None = None,
) -> ProjectDownloadDetail:
    """
    Updates an existing download snapshot in database table "dev_project_downloads", only fields that is not None are changed
    Args:
        download_id: ID of the snapshot to update
        project_id: New project ID the snapshot belongs to, must exist, None if not change
        date: New date of the snapshot, None if not change
        platform: New platform of the snapshot, None if not change
        download_count: New download count, None if not change
        star_count: New star count, None if not change

    Returns:
        The updated download snapshot record
    """
    with SyncSessionLocal() as session:
        download = session.get(ProjectDownload, download_id)
        if download is None:
            raise ValueError(f'Download snapshot with id {download_id} not found')
        if project_id is not None:
            project = session.get(DevProject, project_id)
            if project is None:
                raise ValueError(f'Dev project with id {project_id} not found')
            download.project_id = project_id
        if date is not None:
            download.date = date
        if platform is not None:
            download.platform = platform
        if download_count is not None:
            download.download_count = download_count
        if star_count is not None:
            download.star_count = star_count
        session.commit()
        session.refresh(download)

    return ProjectDownloadDetail.model_validate(download, from_attributes=True)

@tool
def delete_project_download(download_id: int) -> DeleteOutput:
    """
    Deletes a download snapshot from database table "dev_project_downloads"
    Args:
        download_id: ID of the snapshot to delete

    Returns:
        ID of the deleted snapshot with a confirmation message
    """
    with SyncSessionLocal() as session:
        download = session.get(ProjectDownload, download_id)
        if download is None:
            raise ValueError(f'Download snapshot with id {download_id} not found')
        session.delete(download)
        session.commit()

    return DeleteOutput(id=download_id, message=f'Download snapshot {download_id} deleted')

##### HR #####
class DepartmentDetail(BaseModel):
    id: int
    code: str
    name: str
    manager_id: int | None
    created_at: datetime
    updated_at: datetime

class GetDepartmentsOutput(BaseModel):
    department_detail: list[DepartmentDetail]
    total: int

@tool
def get_departments(
    department_id: int | None = None,
    code: str | None = None,
    name: str | None = None,
    manager_id: int | None = None,
) -> GetDepartmentsOutput | None:
    """
    Gets department information from database table "departments", filtered by parameters that is not None
    Args:
        department_id: Target department ID to query, None if not filter by ID
        code: Target department code (exact match), None if not filter by code
        name: Part of the department name (case-insensitive contains), None if not filter by name
        manager_id: User ID of the department manager, None if not filter by manager

    Returns:
        Department data, each department listed in `GetDepartmentsOutput.department_detail` with count in `total`, None if no department fits condition
    """
    stmt = select(Department)
    if department_id is not None:
        stmt = stmt.where(Department.id == department_id)
    if code is not None:
        stmt = stmt.where(Department.code == code)
    if name is not None:
        stmt = stmt.where(Department.name.ilike(f'%{name}%'))
    if manager_id is not None:
        stmt = stmt.where(Department.manager_id == manager_id)

    with SyncSessionLocal() as session:
        departments = (session.execute(stmt)).scalars().all()

    if not departments:
        return None
    return GetDepartmentsOutput(
        department_detail=[DepartmentDetail.model_validate(d, from_attributes=True) for d in departments],
        total=len(departments),
    )

@tool
def create_department(code: str, name: str, manager_id: int | None = None) -> DepartmentDetail:
    """
    Creates a new department into database table "departments"
    Args:
        code: Short unique department code, must not already exist
        name: Department name
        manager_id: User ID of the department manager, must exist, None if not given

    Returns:
        The created department record
    """
    with SyncSessionLocal() as session:
        existing_department = session.execute(select(Department).where(Department.code == code)).scalar_one_or_none()
        if existing_department is not None:
            raise ValueError(f'Department with code {code} already exists')
        if manager_id is not None and session.get(User, manager_id) is None:
            raise ValueError(f'User with id {manager_id} not found')

        department = Department(code=code, name=name, manager_id=manager_id)
        session.add(department)
        session.commit()
        session.refresh(department)

    return DepartmentDetail.model_validate(department, from_attributes=True)

@tool
def update_department(
    department_id: int,
    code: str | None = None,
    name: str | None = None,
    manager_id: int | None = None,
) -> DepartmentDetail:
    """
    Updates an existing department in database table "departments", only fields that is not None are changed
    Args:
        department_id: ID of the department to update
        code: New department code, must not be used by another department, None if not change
        name: New department name, None if not change
        manager_id: New manager user ID, must exist, None if not change

    Returns:
        The updated department record
    """
    with SyncSessionLocal() as session:
        department = session.get(Department, department_id)
        if department is None:
            raise ValueError(f'Department with id {department_id} not found')
        if code is not None and code != department.code:
            existing_department = session.execute(select(Department).where(Department.code == code)).scalar_one_or_none()
            if existing_department is not None:
                raise ValueError(f'Department with code {code} already exists')
            department.code = code
        if name is not None:
            department.name = name
        if manager_id is not None:
            if session.get(User, manager_id) is None:
                raise ValueError(f'User with id {manager_id} not found')
            department.manager_id = manager_id
        session.commit()
        session.refresh(department)

    return DepartmentDetail.model_validate(department, from_attributes=True)

@tool
def delete_department(department_id: int) -> DeleteOutput:
    """
    Deletes a department from database table "departments"
    Args:
        department_id: ID of the department to delete

    Returns:
        ID of the deleted department with a confirmation message
    """
    with SyncSessionLocal() as session:
        department = session.get(Department, department_id)
        if department is None:
            raise ValueError(f'Department with id {department_id} not found')
        session.delete(department)
        session.commit()

    return DeleteOutput(id=department_id, message=f'Department {department_id} deleted')

class UserAttendanceDetail(BaseModel):
    id: int
    user_id: int
    date: date_type
    clocked_in: datetime
    clocked_out: datetime | None
    hours: float

class GetAttendanceOutput(BaseModel):
    user_detail: list[UserAttendanceDetail]
    total_hours: float

def _attendance_detail(a: AttendanceLog) -> UserAttendanceDetail:
    """
    Converts an attendance log row to its output model, deriving hours from the clock times when `total_hours` is not stored
    Args:
        a: Attendance log row

    Returns:
        Attendance detail with `hours` of 0.0 when the row has no clock-out
    """
    if a.total_hours is not None:
        hours = float(a.total_hours)
    elif a.clock_out is not None:
        hours = (a.clock_out - a.clock_in).total_seconds() / 3600
    else:
        hours = 0.0
    return UserAttendanceDetail(
        id=a.id,
        user_id=a.user_id,
        date=a.date,
        clocked_in=a.clock_in,
        clocked_out=a.clock_out,
        hours=hours,
    )

@tool
def get_attendance(
    start_date: date_type,
    end_date: date_type,
    user_id: int | None = None,
    include_open: bool = False,
) -> GetAttendanceOutput | None:
    """
    Gets attendance logs from database table "attendance_logs" in provided duration, filtered by parameters that is not None
    Args:
        start_date: Start period to query attendance (inclusive, by date)
        end_date: End period to query attendance (inclusive, by date)
        user_id: User ID whose logs to query, None if query all users
        include_open: True to also return logs without a clock-out (still clocked in, hours 0.0), False to return completed logs only

    Returns:
        Attendance logs in provided duration, each user/day data listed in `GetAttendanceOutput.user_detail` with summed hours in `total_hours`, None if no log fits condition
    """
    stmt = select(AttendanceLog)
    stmt = stmt.where(AttendanceLog.date >= start_date)
    stmt = stmt.where(AttendanceLog.date <= end_date)
    if user_id is not None:
        stmt = stmt.where(AttendanceLog.user_id == user_id)
    if not include_open:
        stmt = stmt.where(AttendanceLog.clock_out.is_not(None))

    with SyncSessionLocal() as session:
        logs = (session.execute(stmt)).scalars().all()

    if not logs:
        return None
    user_detail = [_attendance_detail(a) for a in logs]
    return GetAttendanceOutput(
        user_detail=user_detail,
        total_hours=sum(d.hours for d in user_detail),
    )

@tool
def create_attendance(
    user_id: int,
    date: date_type,
    clock_in: datetime,
    clock_out: datetime | None = None,
) -> UserAttendanceDetail:
    """
    Creates a new attendance log into database table "attendance_logs", total hours are computed when both clock times are given
    Args:
        user_id: ID of the user who clocks in, must exist
        date: Working date of the log
        clock_in: Clock-in time
        clock_out: Clock-out time, None if the user is still clocked in

    Returns:
        The created attendance log record
    """
    if clock_out is not None and clock_out < clock_in:
        raise ValueError('Clock-out time must not be earlier than clock-in time')

    with SyncSessionLocal() as session:
        if session.get(User, user_id) is None:
            raise ValueError(f'User with id {user_id} not found')

        attendance = AttendanceLog(
            user_id=user_id,
            date=date,
            clock_in=clock_in,
            clock_out=clock_out,
            total_hours=(clock_out - clock_in).total_seconds() / 3600 if clock_out is not None else None,
        )
        session.add(attendance)
        session.commit()
        session.refresh(attendance)

    return _attendance_detail(attendance)

@tool
def update_attendance(
    attendance_id: int,
    clock_in: datetime | None = None,
    clock_out: datetime | None = None,
    total_hours: float | None = None,
) -> UserAttendanceDetail:
    """
    Updates an existing attendance log in database table "attendance_logs", only fields that is not None are changed; total hours are recomputed from the clock times when a clock time changes and `total_hours` is not given
    Args:
        attendance_id: ID of the attendance log to update
        clock_in: New clock-in time, None if not change
        clock_out: New clock-out time (use this to clock a user out), None if not change
        total_hours: Explicit total hours to store, None to compute from the clock times

    Returns:
        The updated attendance log record
    """
    with SyncSessionLocal() as session:
        attendance = session.get(AttendanceLog, attendance_id)
        if attendance is None:
            raise ValueError(f'Attendance log with id {attendance_id} not found')
        if clock_in is not None:
            attendance.clock_in = clock_in
        if clock_out is not None:
            attendance.clock_out = clock_out
        if attendance.clock_out is not None and attendance.clock_out < attendance.clock_in:
            raise ValueError('Clock-out time must not be earlier than clock-in time')
        if total_hours is not None:
            attendance.total_hours = total_hours
        elif (clock_in is not None or clock_out is not None) and attendance.clock_out is not None:
            attendance.total_hours = (attendance.clock_out - attendance.clock_in).total_seconds() / 3600
        session.commit()
        session.refresh(attendance)

    return _attendance_detail(attendance)

@tool
def delete_attendance(attendance_id: int) -> DeleteOutput:
    """
    Deletes an attendance log from database table "attendance_logs"
    Args:
        attendance_id: ID of the attendance log to delete

    Returns:
        ID of the deleted attendance log with a confirmation message
    """
    with SyncSessionLocal() as session:
        attendance = session.get(AttendanceLog, attendance_id)
        if attendance is None:
            raise ValueError(f'Attendance log with id {attendance_id} not found')
        session.delete(attendance)
        session.commit()

    return DeleteOutput(id=attendance_id, message=f'Attendance log {attendance_id} deleted')

class GetLeavesDetail(BaseModel):
    id: int
    user_id: int
    leave_type: str
    start_date: date_type
    end_date: date_type
    reason: str | None = None
    status: str
    approved_by_id: int | None = None

class GetLeavesOutput(BaseModel):
    leave_detail: list[GetLeavesDetail]
    total: int

@tool
def get_leaves(
    user_id: int | None = None,
    full_name: str | None = None,
    start_date: date_type | None = None,
    end_date: date_type | None = None,
    status: Literal["pending", "approved", "rejected"] | None = None,
) -> GetLeavesOutput | None:
    """
    Gets leave requests of a user from database table "leave_requests", should at least provide user_id or full_name or will raise ValueError
    Args:
        user_id: ID of the user whose leaves to query, None if identify the user by full_name
        full_name: Full name of the user whose leaves to query (exact match), None if identify the user by user_id
        start_date: Start of the period; leaves ending on or after this date are returned, None if not filter by start date
        end_date: End of the period; leaves starting on or before this date are returned, None if not filter by end date
        status: Status of the leave requests to filter by, None if not filter by status

    Returns:
        Leave requests in provided criteria, each listed in `GetLeavesOutput.leave_detail` with count in `total`, None if no leave request fits condition
    """
    if user_id is None and full_name is None:
        raise ValueError('Must provide at least one of user_id or full_name')
    if start_date is not None and end_date is not None and start_date > end_date:
        raise ValueError('Start date must be earlier than end date')

    stmt = select(LeaveRequest)
    if user_id is not None:
        stmt = stmt.where(LeaveRequest.user_id == user_id)
    if full_name is not None:
        stmt = stmt.join(User, LeaveRequest.user_id == User.id).where(User.full_name == full_name)
    if start_date is not None:
        stmt = stmt.where(LeaveRequest.end_date >= start_date)
    if end_date is not None:
        stmt = stmt.where(LeaveRequest.start_date <= end_date)
    if status is not None:
        stmt = stmt.where(LeaveRequest.status == status)

    with SyncSessionLocal() as session:
        leaves = (session.execute(stmt)).scalars().all()

    if not leaves:
        return None
    return GetLeavesOutput(
        leave_detail=[GetLeavesDetail.model_validate(e, from_attributes=True) for e in leaves],
        total=len(leaves),
    )

@tool
def create_leave_request(
    user_id: int,
    leave_type: Literal["sick", "annual", "unpaid", "parental"],
    start_date: date_type,
    end_date: date_type,
    reason: str | None = None,
) -> GetLeavesDetail:
    """
    Creates a new leave request into database table "leave_requests" with status pending
    Args:
        user_id: ID of the user who requests the leave, must exist
        leave_type: Type of the leave
        start_date: First day of the leave
        end_date: Last day of the leave (inclusive), must not be earlier than start_date
        reason: Reason of the leave, None if not given

    Returns:
        The created leave request record
    """
    if end_date < start_date:
        raise ValueError('End date must not be earlier than start date')

    with SyncSessionLocal() as session:
        if session.get(User, user_id) is None:
            raise ValueError(f'User with id {user_id} not found')

        leave = LeaveRequest(
            user_id=user_id,
            leave_type=leave_type,
            start_date=start_date,
            end_date=end_date,
            reason=reason,
            status='pending',
        )
        session.add(leave)
        session.commit()
        session.refresh(leave)

    return GetLeavesDetail.model_validate(leave, from_attributes=True)

@tool
def review_leave_request(
    leave_request_id: int,
    decision: Literal["approved", "rejected"],
    approved_by_id: int,
) -> GetLeavesDetail:
    """
    Approves or rejects a leave request in database table "leave_requests"
    Args:
        leave_request_id: ID of the leave request to review
        decision: New status of the leave request
        approved_by_id: ID of the user who makes the decision, must exist

    Returns:
        The reviewed leave request record
    """
    with SyncSessionLocal() as session:
        leave = session.get(LeaveRequest, leave_request_id)
        if leave is None:
            raise ValueError(f'Leave request with id {leave_request_id} not found')
        if session.get(User, approved_by_id) is None:
            raise ValueError(f'User with id {approved_by_id} not found')
        leave.status = decision
        leave.approved_by_id = approved_by_id
        session.commit()
        session.refresh(leave)

    return GetLeavesDetail.model_validate(leave, from_attributes=True)

@tool
def delete_leave_request(leave_request_id: int) -> DeleteOutput:
    """
    Deletes a leave request from database table "leave_requests"
    Args:
        leave_request_id: ID of the leave request to delete

    Returns:
        ID of the deleted leave request with a confirmation message
    """
    with SyncSessionLocal() as session:
        leave = session.get(LeaveRequest, leave_request_id)
        if leave is None:
            raise ValueError(f'Leave request with id {leave_request_id} not found')
        session.delete(leave)
        session.commit()

    return DeleteOutput(id=leave_request_id, message=f'Leave request {leave_request_id} deleted')

class PaycheckDetail(BaseModel):
    id: int
    user_id: int
    pay_period_start: date_type
    pay_period_end: date_type
    base_salary: float
    allowances: float
    deductions: float
    net_pay: float
    payment_date: date_type
    status: str
    created_at: datetime
    updated_at: datetime

class GetPaychecksOutput(BaseModel):
    paycheck_detail: list[PaycheckDetail]
    total: float

@tool
def get_paychecks(
    user_id: int | None = None,
    paycheck_id: int | None = None,
    period_start: date_type | None = None,
    period_end: date_type | None = None,
    status: Literal["draft", "paid"] | None = None,
) -> GetPaychecksOutput | None:
    """
    Gets paychecks from database table "paychecks", filtered by parameters that is not None
    Args:
        user_id: ID of the user the paychecks belong to, None if not filter by user
        paycheck_id: Target paycheck ID to query, None if not filter by ID
        period_start: Start of the period; paychecks whose pay period ends on or after this date are returned, None if not filter by start
        period_end: End of the period; paychecks whose pay period starts on or before this date are returned, None if not filter by end
        status: Status of the paychecks to filter by, None if not filter by status

    Returns:
        Paycheck data, each paycheck listed in `GetPaychecksOutput.paycheck_detail` with summed net pay in `total`, None if no paycheck fits condition
    """
    stmt = select(Paycheck)
    if user_id is not None:
        stmt = stmt.where(Paycheck.user_id == user_id)
    if paycheck_id is not None:
        stmt = stmt.where(Paycheck.id == paycheck_id)
    if period_start is not None:
        stmt = stmt.where(Paycheck.pay_period_end >= period_start)
    if period_end is not None:
        stmt = stmt.where(Paycheck.pay_period_start <= period_end)
    if status is not None:
        stmt = stmt.where(Paycheck.status == status)

    with SyncSessionLocal() as session:
        paychecks = (session.execute(stmt)).scalars().all()

    if not paychecks:
        return None
    total = float(sum(p.net_pay for p in paychecks))
    return GetPaychecksOutput(
        paycheck_detail=[PaycheckDetail.model_validate(p, from_attributes=True) for p in paychecks],
        total=total,
    )

@tool
def create_paycheck(
    user_id: int,
    pay_period_start: date_type,
    pay_period_end: date_type,
    base_salary: float,
    payment_date: date_type,
    allowances: float = 0.0,
    deductions: float = 0.0,
    net_pay: float | None = None,
    status: Literal["draft", "paid"] = "draft",
) -> PaycheckDetail:
    """
    Creates a new paycheck into database table "paychecks", net pay is computed as base_salary + allowances - deductions when not given
    Args:
        user_id: ID of the user the paycheck belongs to, must exist
        pay_period_start: First day of the pay period
        pay_period_end: Last day of the pay period, must not be earlier than pay_period_start
        base_salary: Base salary of the period
        payment_date: Date the paycheck is (or will be) paid
        allowances: Allowances added on top of base salary, defaults to 0
        deductions: Deductions taken from the pay, defaults to 0
        net_pay: Explicit net pay to store, None to compute it
        status: Status of the paycheck, defaults to draft

    Returns:
        The created paycheck record
    """
    if pay_period_end < pay_period_start:
        raise ValueError('Pay period end must not be earlier than pay period start')

    with SyncSessionLocal() as session:
        if session.get(User, user_id) is None:
            raise ValueError(f'User with id {user_id} not found')

        paycheck = Paycheck(
            user_id=user_id,
            pay_period_start=pay_period_start,
            pay_period_end=pay_period_end,
            base_salary=base_salary,
            allowances=allowances,
            deductions=deductions,
            net_pay=net_pay if net_pay is not None else base_salary + allowances - deductions,
            payment_date=payment_date,
            status=status,
        )
        session.add(paycheck)
        session.commit()
        session.refresh(paycheck)

    return PaycheckDetail.model_validate(paycheck, from_attributes=True)

@tool
def update_paycheck(
    paycheck_id: int,
    pay_period_start: date_type | None = None,
    pay_period_end: date_type | None = None,
    base_salary: float | None = None,
    allowances: float | None = None,
    deductions: float | None = None,
    net_pay: float | None = None,
    payment_date: date_type | None = None,
    status: Literal["draft", "paid"] | None = None,
) -> PaycheckDetail:
    """
    Updates an existing paycheck in database table "paychecks", only fields that is not None are changed; net pay is recomputed when a salary component changes and `net_pay` is not given
    Args:
        paycheck_id: ID of the paycheck to update
        pay_period_start: New first day of the pay period, None if not change
        pay_period_end: New last day of the pay period, None if not change
        base_salary: New base salary, None if not change
        allowances: New allowances, None if not change
        deductions: New deductions, None if not change
        net_pay: Explicit net pay to store, None to keep or recompute it
        payment_date: New payment date, None if not change
        status: New status (use paid to mark the paycheck as paid), None if not change

    Returns:
        The updated paycheck record
    """
    with SyncSessionLocal() as session:
        paycheck = session.get(Paycheck, paycheck_id)
        if paycheck is None:
            raise ValueError(f'Paycheck with id {paycheck_id} not found')
        if pay_period_start is not None:
            paycheck.pay_period_start = pay_period_start
        if pay_period_end is not None:
            paycheck.pay_period_end = pay_period_end
        if paycheck.pay_period_end < paycheck.pay_period_start:
            raise ValueError('Pay period end must not be earlier than pay period start')
        if base_salary is not None:
            paycheck.base_salary = base_salary
        if allowances is not None:
            paycheck.allowances = allowances
        if deductions is not None:
            paycheck.deductions = deductions
        if net_pay is not None:
            paycheck.net_pay = net_pay
        elif base_salary is not None or allowances is not None or deductions is not None:
            paycheck.net_pay = float(paycheck.base_salary) + float(paycheck.allowances) - float(paycheck.deductions)
        if payment_date is not None:
            paycheck.payment_date = payment_date
        if status is not None:
            paycheck.status = status
        session.commit()
        session.refresh(paycheck)

    return PaycheckDetail.model_validate(paycheck, from_attributes=True)

@tool
def delete_paycheck(paycheck_id: int) -> DeleteOutput:
    """
    Deletes a paycheck from database table "paychecks"
    Args:
        paycheck_id: ID of the paycheck to delete

    Returns:
        ID of the deleted paycheck with a confirmation message
    """
    with SyncSessionLocal() as session:
        paycheck = session.get(Paycheck, paycheck_id)
        if paycheck is None:
            raise ValueError(f'Paycheck with id {paycheck_id} not found')
        session.delete(paycheck)
        session.commit()

    return DeleteOutput(id=paycheck_id, message=f'Paycheck {paycheck_id} deleted')
