"""alter_payment_date_to_date_in_paycheck

Revision ID: 0f552d5b9710
Revises: b236efb14d55
Create Date: 2026-07-26 15:33:31.721059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f552d5b9710'
down_revision: Union[str, Sequence[str], None] = 'b236efb14d55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('paychecks', 'payment_date',
               existing_type=sa.NUMERIC(),
               type_=sa.Date(),
               existing_nullable=False,
               postgresql_using="CURRENT_DATE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('paychecks', 'payment_date',
               existing_type=sa.Date(),
               type_=sa.NUMERIC(),
               existing_nullable=False,
               postgresql_using="extract(day from payment_date)")
    # ### end Alembic commands ###
