"""add_permission_fields

Revision ID: 9fbc24b11fbd
Revises: 0f552d5b9710
Create Date: 2026-07-29 00:45:24.025657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fbc24b11fbd'
down_revision: Union[str, Sequence[str], None] = '0f552d5b9710'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_finance_access', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('has_scm_access', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('has_hr_access', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('has_dev_access', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_dev_access')
    op.drop_column('users', 'has_hr_access')
    op.drop_column('users', 'has_scm_access')
    op.drop_column('users', 'has_finance_access')
    # ### end Alembic commands ###
