"""add_employee_fields_and_user_id

Revision ID: b236efb14d55
Revises: bece9235ab90
Create Date: 2026-07-26 14:02:37.048596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b236efb14d55'
down_revision: Union[str, Sequence[str], None] = 'bece9235ab90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_postings_id'), table_name='job_postings')
    op.drop_table('job_postings')
    op.add_column('employees', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('employees', sa.Column('first_name', sa.String(length=50), nullable=False))
    op.add_column('employees', sa.Column('last_name', sa.String(length=50), nullable=False))
    op.alter_column('employees', 'job_title',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_foreign_key(None, 'employees', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('employees', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.alter_column('employees', 'job_title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('employees', 'last_name')
    op.drop_column('employees', 'first_name')
    op.drop_column('employees', 'user_id')
    op.create_table('job_postings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('job_postings_department_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('job_postings_pkey'))
    )
    op.create_index(op.f('ix_job_postings_id'), 'job_postings', ['id'], unique=False)
    # ### end Alembic commands ###
